### ISSUE TITLE
安装时报 SyntaxError: Unexpected identifier 错误

### ISSUE THREAD

**Issue by qq291462491** [guowenfh/geek-time-topdf#21]
`/usr/local/lib/node_modules/geek-time-topdf/node_modules/_pkg-dir@4.2.0@pkg-dir/index.js:5
const pkgDir = async cwd => {
                     ^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/geek-time-topdf/node_modules/_husky@3.1.0@husky/lib/installer/index.js:8:35)
    at Module._compile (module.js:571:32)
[npminstall:runscript:error] geek-time-topdf@4.0.3 scripts.postinstall run "node node_modules/husky/lib/installer/bin install" error: RunScriptError: Run "sh -c node node_modules/husky/lib/installer/bin install" error, exit code 1
Install fail! RunScriptError: post install error, please remove node_modules before retry!
Run "sh -c node node_modules/husky/lib/installer/bin install" error, exit code 1
RunScriptError: post install error, please remove node_modules before retry!
Run "sh -c node node_modules/husky/lib/installer/bin install" error, exit code 1
    at ChildProcess.proc.on.code (/usr/local/lib/node_modules/cnpm/node_modules/runscript/index.js:96:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npminstall version: 3.25.0`

**Comment by qq291462491** [comment]
Mac OS Mojave 10.14.6

**Comment by mydaoyuan** [comment]
> Mac OS Mojave 10.14.6

node 版本是多少，尝试清除 npm 缓存。看看还会不会还报错
