### ISSUE TITLE
求指教

### ISSUE THREAD

**Issue by UniverseJun** [guowenfh/geek-time-topdf#6]
用户登录失败 Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"
    at Launcher.launch (/usr/local/lib/node_modules/geek-time-topdf/node_modules/puppeteer/lib/Launcher.js:119:15)
    at <anonymous>
TypeError: Cannot read property 'map' of undefined
    at searchPrint (/usr/local/lib/node_modules/geek-time-topdf/src/index.js:28:38)
    at Command.start (/usr/local/lib/node_modules/geek-time-topdf/src/index.js:14:11)
    at <anonymous>

**Comment by UniverseJun** [comment]
npm install 已经执行完成了

**Comment by guowenfh** [comment]
@UniverseJun 提示已经很明显了哇，Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"。 依赖安装失败了，需要 删除 node_modules 重新安装一下  推荐使用 cnpm i

**Comment by guowenfh** [comment]
直接用 npm install ，执行完了并不代表都成功了。。 有依赖 Chromium 默认地址是在 国外的
